---
development:
  cloud_name: <%= ENV["MYRECIPES_CLOUDINARY_CLOUD_NAME"] %>
  api_key: <%= ENV["MYRECIPES_CLOUDINARY_API_KEY"] %>
  api_secret: <%= ENV["MYRECIPES_CLOUDINARY_API_SECRET"] %>
  enhance_image_tag: <%= ENV["MYRECIPES_CLOUDINARY_ENHANCE_IMAGE_TAG"] %>
  static_image_support: <%= ENV["MYRECIPES_CLOUDINARY_STATIC_IMAGE_SUPPORT"] %>
  secure: <%= ENV["MYRECIPES_CLOUDINARY_SECURE"] %>
test:
  cloud_name: ""
  api_key: ""
  api_secret: ""
